// gen-fixtures reads fixtures/**/*.json and generates server/fixtures/library.go
// containing a typed map[string]Fixture ready for import.
//
// Usage: go run ./tools/gen-fixtures
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type fixture struct {
	Name         string   `json:"name"`
	ShortName    string   `json:"shortName"`
	Manufacturer string   `json:"manufacturer"`
	ChannelCount int      `json:"channelCount"`
	Channels     []string `json:"channels"`
}

func main() {
	fixturesDir := "fixtures"
	outFile := filepath.Join("server", "fixtures", "library.go")

	var keys []string
	fixtures := map[string]fixture{}

	err := filepath.Walk(fixturesDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() || filepath.Ext(path) != ".json" {
			return nil
		}

		data, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("read %s: %w", path, err)
		}

		var f fixture
		if err := json.Unmarshal(data, &f); err != nil {
			return fmt.Errorf("parse %s: %w", path, err)
		}

		if f.ChannelCount != len(f.Channels) {
			return fmt.Errorf("%s: channelCount %d != len(channels) %d", path, f.ChannelCount, len(f.Channels))
		}

		// Key is relative path without .json extension, e.g. "generic/rgb-3ch"
		rel, _ := filepath.Rel(fixturesDir, path)
		key := strings.TrimSuffix(rel, ".json")
		key = filepath.ToSlash(key) // normalize to forward slashes

		keys = append(keys, key)
		fixtures[key] = f

		return nil
	})
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}

	sort.Strings(keys)

	var b strings.Builder
	b.WriteString("// Code generated by tools/gen-fixtures — DO NOT EDIT.\n\n")
	b.WriteString("package fixtures\n\n")
	b.WriteString("// Fixture represents a single fixture at a single channel count.\n")
	b.WriteString("type Fixture struct {\n")
	b.WriteString("\tName         string   `json:\"name\"`\n")
	b.WriteString("\tShortName    string   `json:\"shortName\"`\n")
	b.WriteString("\tManufacturer string   `json:\"manufacturer\"`\n")
	b.WriteString("\tChannelCount int      `json:\"channelCount\"`\n")
	b.WriteString("\tChannels     []string `json:\"channels\"`\n")
	b.WriteString("}\n\n")
	b.WriteString("// Library maps fixture keys (e.g. \"generic/rgb-3ch\") to their definitions.\n")
	b.WriteString("var Library = map[string]Fixture{\n")

	for _, key := range keys {
		f := fixtures[key]
		b.WriteString(fmt.Sprintf("\t%q: {\n", key))
		b.WriteString(fmt.Sprintf("\t\tName:         %q,\n", f.Name))
		b.WriteString(fmt.Sprintf("\t\tShortName:    %q,\n", f.ShortName))
		b.WriteString(fmt.Sprintf("\t\tManufacturer: %q,\n", f.Manufacturer))
		b.WriteString(fmt.Sprintf("\t\tChannelCount: %d,\n", f.ChannelCount))
		b.WriteString("\t\tChannels:     []string{")
		for i, ch := range f.Channels {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(fmt.Sprintf("%q", ch))
		}
		b.WriteString("},\n")
		b.WriteString("\t},\n")
	}

	b.WriteString("}\n")

	if err := os.MkdirAll(filepath.Dir(outFile), 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "error creating output dir: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outFile, []byte(b.String()), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "error writing %s: %v\n", outFile, err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s with %d fixtures\n", outFile, len(keys))
}
