// Code generated by tools/gen-fixtures — DO NOT EDIT.

package fixtures

// Fixture represents a single fixture at a single channel count.
type Fixture struct {
	Name         string
	ShortName    string
	Manufacturer string
	ChannelCount int
	Channels     []string
}

// Library maps fixture keys (e.g. "generic/rgb-3ch") to their definitions.
var Library = map[string]Fixture{
	"american-dj/mega-par-profile-plus-4ch": {
		Name:         "American DJ Mega Par Profile Plus (4ch)",
		ShortName:    "Mega Par 4ch",
		Manufacturer: "American DJ",
		ChannelCount: 4,
		Channels:     []string{"Red", "Green", "Blue", "UV"},
	},
	"american-dj/mega-par-profile-plus-6ch": {
		Name:         "American DJ Mega Par Profile Plus (6ch)",
		ShortName:    "Mega Par 6ch",
		Manufacturer: "American DJ",
		ChannelCount: 6,
		Channels:     []string{"Red", "Green", "Blue", "UV", "Strobe", "Dimmer"},
	},
	"american-dj/mega-par-profile-plus-9ch": {
		Name:         "American DJ Mega Par Profile Plus (9ch)",
		ShortName:    "Mega Par 9ch",
		Manufacturer: "American DJ",
		ChannelCount: 9,
		Channels:     []string{"Red", "Green", "Blue", "UV", "Strobe", "Dimmer", "Program Mode", "Program Selection", "Program Speed"},
	},
	"chauvet-dj/slimpar-pro-h-usb-12ch": {
		Name:         "Chauvet DJ SlimPAR Pro H USB (12ch)",
		ShortName:    "SlimPAR 12ch",
		Manufacturer: "Chauvet DJ",
		ChannelCount: 12,
		Channels:     []string{"Dimmer", "Red", "Green", "Blue", "Amber", "White", "UV", "Strobe", "Color Macros", "Mode", "Program Speed", "Dimmer Speed"},
	},
	"chauvet-dj/slimpar-pro-h-usb-6ch": {
		Name:         "Chauvet DJ SlimPAR Pro H USB (6ch)",
		ShortName:    "SlimPAR 6ch",
		Manufacturer: "Chauvet DJ",
		ChannelCount: 6,
		Channels:     []string{"Red", "Green", "Blue", "Amber", "White", "UV"},
	},
	"chauvet-dj/slimpar-pro-h-usb-7ch": {
		Name:         "Chauvet DJ SlimPAR Pro H USB (7ch)",
		ShortName:    "SlimPAR 7ch",
		Manufacturer: "Chauvet DJ",
		ChannelCount: 7,
		Channels:     []string{"Dimmer", "Red", "Green", "Blue", "Amber", "White", "UV"},
	},
	"generic/moving-head-16ch": {
		Name:         "Generic Moving Head (16ch)",
		ShortName:    "Mover 16ch",
		Manufacturer: "Generic",
		ChannelCount: 16,
		Channels:     []string{"Pan", "Pan Fine", "Tilt", "Tilt Fine", "Dimmer", "Red", "Green", "Blue", "White", "Strobe", "Color", "Gobo", "Gobo Rotation", "Prism", "Speed", "Focus"},
	},
	"generic/moving-head-8ch": {
		Name:         "Generic Moving Head (8ch)",
		ShortName:    "Mover 8ch",
		Manufacturer: "Generic",
		ChannelCount: 8,
		Channels:     []string{"Pan", "Tilt", "Dimmer", "Red", "Green", "Blue", "White", "Strobe"},
	},
	"generic/rgb-3ch": {
		Name:         "Generic RGB Par (3ch)",
		ShortName:    "RGB 3ch",
		Manufacturer: "Generic",
		ChannelCount: 3,
		Channels:     []string{"Red", "Green", "Blue"},
	},
	"generic/rgbaw-6ch": {
		Name:         "Generic RGBAW Par (6ch)",
		ShortName:    "RGBAW 6ch",
		Manufacturer: "Generic",
		ChannelCount: 6,
		Channels:     []string{"Dimmer", "Red", "Green", "Blue", "Amber", "White"},
	},
	"generic/rgbawuv-7ch": {
		Name:         "Generic RGBAW+UV Par (7ch)",
		ShortName:    "RGBAW+UV 7ch",
		Manufacturer: "Generic",
		ChannelCount: 7,
		Channels:     []string{"Dimmer", "Red", "Green", "Blue", "Amber", "White", "UV"},
	},
	"generic/rgbw-4ch": {
		Name:         "Generic RGBW Par (4ch)",
		ShortName:    "RGBW 4ch",
		Manufacturer: "Generic",
		ChannelCount: 4,
		Channels:     []string{"Red", "Green", "Blue", "White"},
	},
}
