import * as esbuild from 'esbuild'

const watch = process.argv.includes('--watch')

const config = {
  entryPoints: ['src/main.ts'],
  bundle: true,
  outfile: 'dist/main.js',
  target: 'es6',
  platform: 'neutral',
  format: 'iife',
  // Max does not support ES modules — everything must be bundled into one
  // self-contained IIFE. Shared packages (@ableton-dmx/*) are bundled in.
  //
  // Max globals (post, outlet, inlet, Task, etc.) are NOT available at
  // bundle time — they are injected by the Max runtime. Do not import or
  // mock them here; they are accessed via the dependency injection pattern
  // in main.ts only.
  minify: false,  // keep readable for debugging in Ableton's JS console
  banner: {
    // Silence strict mode issues that can arise from bundled output in Max
    js: '// Auto-generated by esbuild. Do not edit.\n'
  }
}

if (watch) {
  const ctx = await esbuild.context({
    ...config,
    plugins: [{
      name: 'rebuild-notify',
      setup(build) {
        build.onEnd(result => {
          if (result.errors.length > 0) {
            console.error('Build failed:', result.errors)
          } else {
            console.log(`Rebuilt → dist/main.js (${new Date().toLocaleTimeString()})`)
          }
        })
      }
    }]
  })
  await ctx.watch()
  console.log('Watching for changes...')
} else {
  const result = await esbuild.build(config)
  if (result.errors.length > 0) {
    process.exit(1)
  }
  console.log('Build complete → dist/main.js')
}
